In [1]:
import numpy as np

In [15]:
## Definition of Pauli Matrices
Pauli0 = np.matrix([
    [1,0],
    [0,1]
])
PauliX = np.matrix([
    [0,1],
    [1,0]
])
PauliY = np.matrix([
    [0,-1j],
    [1j,0]
])
PauliZ = np.matrix([
    [1,0],
    [0,-1]
])
PauliMats = [Pauli0, PauliX, PauliY, PauliZ]
## Definition of 2 qubit unitary ops basis
TwoQubitPauliOps = [[np.kron(Pop1,Pop2) for Pop2 in PauliMats] for Pop1 in PauliMats]

In [40]:
## Definition of Inner product
def inprod(A,B):
    return np.trace(np.matmul(A.getH(),B))
## Obtain expansion coefficients for matirx
def PauliBasisRep(A):
    ## Computation of expansion coefficients
    ExpCoefs = []
    for OpsList in TwoQubitPauliOps:
        coefs = []
        for Op in OpsList:
            coefs.append(inprod(Op,A))
        ExpCoefs.append(coefs)
    ## return expansion coefficients
    return ExpCoefs

In [41]:
## Definition of CNOT matrix
CNOT = np.matrix([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,0,1],
    [0,0,1,0]
])

In [42]:
## Computation of expansion coefficients
ExpCoefs = PauliBasisRep(CNOT)
print(ExpCoefs)

[[2, 2, 0j, 0], [0, 0, 0j, 0], [0j, 0j, 0j, 0j], [2, -2, 0j, 0]]


In [44]:
CNOT_SUM = np.matrix(np.zeros((4,4)))
for idx in range(4):
    for jdx in range(4):
        CNOT_SUM = CNOT_SUM + 1/4 * ExpCoefs[idx][jdx] * TwoQubitPauliOps[idx][jdx]
## Print hypotetic result
print(CNOT_SUM)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]]


In [45]:
Eigvals, Eigvecs = np.linalg.eig(CNOT)
print(Eigvals)
print(Eigvecs)

[ 1. -1.  1.  1.]
[[ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]]


In [47]:
## Eigenvalues of generating Hamiltonian
HamVals = [0, np.pi, 0, 0]
## Diagonal matrix of generating Hamiltonian
Hdiag = np.diag(HamVals)
## Computational basis representation of gen. Ham.
H = np.matmul(np.matmul(Eigvecs,Hdiag),Eigvecs.getH())
## Print generating Hamiltonian
print(H)

[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          1.57079633 -1.57079633]
 [ 0.          0.         -1.57079633  1.57079633]]


In [48]:
HamCoefs = PauliBasisRep(H)
print(HamCoefs)

[[3.1415926535897927, -3.1415926535897927, 0j, 0.0], [0.0, 0.0, 0j, 0.0], [0j, 0j, 0j, 0j], [-3.1415926535897927, 3.1415926535897927, 0j, 0.0]]
